### ISSUE TITLE
Ability to send keystrokes

### ISSUE THREAD

**Issue by Boscop** [brunoqc/rs-autoit#1]
It would be useful if one could send keystrokes to a window :)

And if one could set the window title match mode:
https://www.autoitscript.com/autoit3/docs/intro/windowsadvanced.htm

Also WinSetOnTop and WinGetHandle.

Btw, there are some crates for dealing with wide strings:
https://starkat99.github.io/widestring-rs/widestring/struct.WideString.html#method.from_str
https://rusty-new-dev.github.io/wcstr/wcstr/struct.WCString.html#method.from_str

**Comment by bbigras** [comment]
I think there's everything, reopen if I forgot something.

Thanks a lot for the report. My str_to_lpcwstr() was very buggy.
